// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKFQRPqsdjrhVTUo6bu9zmKkcwQe4dUmU',
    appId: '1:422192162403:web:ac7c6219c899899654fa56',
    messagingSenderId: '422192162403',
    projectId: 'reword-3',
    authDomain: 'reword-3.firebaseapp.com',
    storageBucket: 'reword-3.firebasestorage.app',
    measurementId: 'G-6STT4BY6BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI_cWsPDMmpyLTxCTLnTAVxpDrJn_IQfc',
    appId: '1:422192162403:android:1057fa74a9ebda4754fa56',
    messagingSenderId: '422192162403',
    projectId: 'reword-3',
    storageBucket: 'reword-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW2LS0PFNbDvyLh4i2C6mnZUHQ6yP7mtE',
    appId: '1:422192162403:ios:e4b20f0b0b9b384954fa56',
    messagingSenderId: '422192162403',
    projectId: 'reword-3',
    storageBucket: 'reword-3.firebasestorage.app',
    iosBundleId: 'com.example.rewordFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW2LS0PFNbDvyLh4i2C6mnZUHQ6yP7mtE',
    appId: '1:422192162403:ios:e4b20f0b0b9b384954fa56',
    messagingSenderId: '422192162403',
    projectId: 'reword-3',
    storageBucket: 'reword-3.firebasestorage.app',
    iosBundleId: 'com.example.rewordFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKFQRPqsdjrhVTUo6bu9zmKkcwQe4dUmU',
    appId: '1:422192162403:web:92b4885624cb2d1e54fa56',
    messagingSenderId: '422192162403',
    projectId: 'reword-3',
    authDomain: 'reword-3.firebaseapp.com',
    storageBucket: 'reword-3.firebasestorage.app',
    measurementId: 'G-E5M5NLDPJW',
  );
}
